// src/components/Legend.svelte
<script lang="ts">
  import type { EntryItem, RadarConfig } from "../logic/radar-config";
  import { createEventDispatcher } from "svelte";
  import Accordion from "./Accordion.svelte";
  import Accordions from "./Accordions.svelte";

  export let rings: RadarConfig["rings"];
  export let quadrants: RadarConfig["quadrants"];
  export let data: EntryItem[];

  const dispatch = createEventDispatcher();

  let openedAccordion = "NONE";
  const toggleAccordion = (e: CustomEvent<string>) => (openedAccordion = e.detail === openedAccordion ? "NONE" : e.detail);
</script>

<ul class="quadrant-list">
  {#each quadrants as quadrant}
    <li class="quadrant-item" data-quadrant-index={quadrant.index}>
      <h2>{quadrant.name}</h2>

      {#each rings as ring}
        <div
          class="ring-wrapper"
          data-ring-index="0"
          style="border-color: {ring.color}"
        >
          <h3 class="ring-label">{ring.name}</h3>
          <Accordions>
            {#each data.sort((a, b) => a.label.localeCompare(b.label)).filter((entry) => {
              return entry.quadrant === quadrant.index && entry.ring === ring.index;
            }) as item}
              <Accordion
                id={item.label}
                {openedAccordion}
                on:accordionSelected={toggleAccordion}
              >
              <span
                slot="title"
                class="entry-item"
                on:mouseover={() => dispatch("mouseover", item)}
                on:mouseout={() => dispatch("mouseout", item)}
                data-label={item.label}>
                  {item.label}
              </span>

                {#if item.description}
                  <hr style="margin-left: 20px; border-top: 1px solid #a4a6a9">

                  <p
                    class="entry-description"
                  >
                    {item.description || ''}

                    {#if item.link}
                      <br>
                      <a class="link" href={item.link} target="_blank">See more ></a>
                    {/if}
                  </p>
                {/if}

              </Accordion>
            {/each}
          </Accordions>
        </div>
      {/each}
    </li>
  {/each}
</ul>

<style>
    .quadrant-list {
        margin: 0;
        padding: 0;
    }

    .quadrant-item {
        margin-bottom: 90px;
    }

    .quadrant-item h2 {
        font-size: 24px;
        font-weight: 700;
    }

    .entry-item {
        display: block;
        line-height: 1.5;
        padding-left: 20px;
        transition: 0.3s;
        cursor: pointer;
    }

    .entry-description {
        display: block;
        padding-left: 20px;
        transition: 0.3s;
        color: #49586E;
        font-size: 14px;
    }

    .ring-wrapper {
        border-left: 3px solid;
        padding: 10px 0 10px 0;
        margin: 10px 0;
    }

    .link {
        color: #49586E;
        font-weight: 700;
        padding: 8px 0;
        float: right;
        text-decoration: none;
    }

    .link:active, .link:hover {
        color: #eb4646;
        transform: translateX(2px);
    }

    .ring-wrapper h3 {
        margin: 0 0 10px 10px;
        color: #a4a6a9;
    }

    .entry-item:hover {
        font-weight: 700;
        transform: translateX(10px);
    }

    li {
        margin: 25px 50px 0 0;
    }

    h3 {
        margin-top: 50px;
    }
</style>

// components/Legend/Legend.tsx
import React, { FC, useState } from 'react';
import { RingConfig, QuadrantConfig, EntryItem } from '../../types/radar.types';
import styles from './Legend.module.css';
import { Radar as RadarD3 } from '../../logic/radar';

type Props = {
  rings: RingConfig[];
  quadrants: QuadrantConfig[];
  entryItems: EntryItem[];
  radar: RadarD3 | null;
};

export const Legend: FC<Props> = ({ radar, rings, quadrants, entryItems }) => {
  const [openedAccordion, setOpenedAccordion] = useState('NONE');

  const handleMouseOver = (label: string) => {
    if (radar !== null) {
      radar.highlightDot(label);
    }
  };

  const handleMouseOut = () => {
    if (radar !== null) {
      radar.hideHighlightDot();
    }
  };

  return (
    <>
      <ul className={styles['quadrant-list']}>
        {quadrants.map((quadrant) => (
          <li
            key={quadrant.index}
            className="quadrant-item"
            data-quadrant-index={quadrant.index}
          >
            <h2>{quadrant.name}</h2>

            {rings.map((ring) => (
              <div
                key={ring.index}
                className={styles['ring-wrapper']}
                data-ring-index="0"
                style={{ borderColor: ring.color }}
              >
                <h3 className={styles['ring-label']}>{ring.name}</h3>

                {entryItems
                  .sort((a, b) => a.label.localeCompare(b.label))
                  .filter(
                    (entry) =>
                      entry.quadrant === quadrant.index &&
                      entry.ring === ring.index
                  )
                  .map((entryItem, index) => (
                    <div key={index}>
                      <div
                        onClick={() =>
                          setOpenedAccordion(
                            openedAccordion === entryItem.label
                              ? 'NONE'
                              : entryItem.label
                          )
                        }
                      >
                        <span
                          key={entryItem.label}
                          className={styles['entry-item']}
                          style={
                            openedAccordion === entryItem.label ? { fontWeight: 700 } : {}
                          }
                          onMouseOver={() => handleMouseOver(entryItem.label)}
                          onMouseOut={handleMouseOut}
                          data-label={entryItem.label}
                        >
                          {entryItem.label}
                        </span>
                      </div>

                      {openedAccordion === entryItem.label && (
                        <div className={styles['collapsible-body']}>
                          {!entryItem.description?.length ||
                            (entryItem.link && (
                              <>
                                <hr
                                  style={{
                                    marginLeft: 20,
                                    borderTop: '1px solid #a4a6a9',
                                  }}
                                />

                                <p className={styles['entry-description']}>
                                  {entryItem.description}

                                  {entryItem.link && (
                                    <>
                                      <br />
                                      <a
                                        className={styles.link}
                                        href={entryItem.link}
                                        target="_blank"
                                      >
                                        See more &gt;
                                      </a>
                                    </>
                                  )}
                                </p>
                              </>
                            ))}
                        </div>
                      )}
                    </div>
                  ))}
              </div>
            ))}
          </li>
        ))}
      </ul>
    </>
  );
};
